begin;
insert into public.leyes (id,titulo,siglas,fecha_publicacion,fecha_ultima_reforma,vigente,temas_clave,url_original,tipo) values ('75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Norma Técnica para la elaboración de Metadatos de los Procesos de Producción de Información Estadística y Geográfica','NT-METADATOS-SNIEG-2025','2025-09-17',null,true,ARRAY['SNIEG','Metadatos','Información Estadística','Información Geográfica','INEGI']::text[],'https://sidof.segob.gob.mx/notas/docFuente/5768007','norma') on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('58fa3c85-3980-55c9-9a29-864149a588ac'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Preámbulo y considerandos','<p>NORMA Técnica para la elaboración de Metadatos de los Procesos de Producción de Información Estadística y Geográfica. Al margen un sello con el Escudo Nacional, que dice: Estados Unidos Mexicanos.- Instituto Nacional de Estadística y Geografía.- Junta de Gobierno. Con fundamento en lo dispuesto en los artículos 26 del apartado B de la Constitución Política de los Estados Unidos Mexicanos; 17, 52, 55 fracciones I y II, 57, 58, 62 y 77, fracción VIII de la Ley del Sistema Nacional de Información Estadística y Geográfica; 5 fracción VIII del Reglamento Interior del Instituto Nacional de Estadística y Geografía, y CONSIDERANDO Que el apartado B del artículo 26 de la Constitución Política de los Estados Unidos Mexicanos determina que el Estado contará con un Sistema Nacional de Información Estadística y Geográfica (Sistema o SNIEG), cuyos datos serán considerados oficiales y además de uso obligatorio para la Federación, las entidades federativas, los municipios y las demarcaciones territoriales de la Ciudad de México, en los términos que establezca la Ley del Sistema Nacional de Información Estadística y Geográfica (Ley del SNIEG). Que la Ley del SNIEG faculta al Instituto Nacional de Estadística y Geografía (Instituto o INEGI), para normar y coordinar el SNIEG, y en su carácter de Unidad Central Coordinadora, le atribuye, entre otras funciones, fomentar las acciones que permitan mantener su operación eficiente, así como la organización y participación de las Unidades del Estado en el Sistema. Que el Instituto deberá dar a conocer y conservar los metadatos o las especificaciones concretas de la aplicación de las metodologías que se hubiesen utilizado en la elaboración de la información estadística y geográfica. Que las Unidades del Estado cuando desarrollen actividades relacionadas con la producción, integración, conservación y difusión de Información de Interés Nacional, deberán resguardar y conservar dicha información, así como los metadatos o las especificaciones concretas de la aplicación de las metodologías que hubiesen utilizado en la producción de esta.</p>
<p>Que las Unidades del Estado deben publicar la información estadística y geográfica con sus metadatos correspondientes, con base en las disposiciones que establezca la Junta de Gobierno. Que los metadatos permiten el uso adecuado de la información estadística y geográfica que se genera en el SNIEG, al facilitar su comprensión mediante la descripción estandarizada de sus características. Que las disposiciones normativas del SNIEG sobre elaboración de metadatos se complementan según su objeto y alcance, estableciendo las directrices para la documentación de los Procesos de Producción y de los conjuntos de datos de información estadística y geográfica. Que el apegarse a los estándares internacionales sobre documentación de metadatos de la información estadística y geográfica es una práctica necesaria, ya que facilita su aprovechamiento y la comparación entre fuentes, tanto nacionales como extranjeras. Que, como órgano superior de dirección del INEGI, la Junta de Gobierno emitió en 2015 la Norma Técnica para la Elaboración de Metadatos para proyectos de generación de Información Estadística Básica y de los componentes estadísticos derivados de proyectos geográficos, mediante Acuerdo 5ª/III/ 2015, del 19 de agosto de 2015. Que la presente Norma permitirá a las personas usuarias de la información estadística y geográfica contar con documentación homogénea y estructurada de los aspectos conceptuales, metodológicos y de calidad tanto de la Información de Interés Nacional como de la información generada por cualquier Proceso de Producción del Instituto. Que los metadatos documentados conforme a la presente Norma Técnica podrán vincularse con los elaborados bajo las disposiciones normativas vigentes en materia de metadatos geográficos y de datos abiertos. Que la presente Norma Técnica se consolidará como el marco general para la documentación de metadatos, y sus instrumentos de apoyo brindan un marco flexible para enriquecerlo con especificaciones de metadatos adicionales, en función de las necesidades del SNIEG. Que la elaboración de la presente Norma Técnica consideró las aportaciones de la Consulta Pública realizada a unidades generadoras y personas usuarias de información estadística y geográfica, y cuenta con la aprobación de los cuatro Comités Ejecutivos de los Subsistemas Nacionales de Información que conforman el SNIEG. Por lo anterior, la Junta de Gobierno del Instituto Nacional de Estadística y Geografía ha tenido a bien emitir la siguiente: NORMA TÉCNICA PARA LA ELABORACIÓN DE METADATOS DE LOS PROCESOS DE PRODUCCIÓN DE INFORMACIÓN ESTADÍSTICA Y GEOGRÁFICA</p>','preambulo',0,'Preámbulo',null,null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('8b683498-22aa-5996-af8e-b0b01faa906d'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 1','<p>Artículo 1.- La presente Norma tiene por objeto establecer las disposiciones para elaborar los metadatos de los Procesos de Producción mediante los que se genera Información de Interés Nacional, así como la información pública oficial a cargo del INEGI, con el propósito de favorecer su descripción estandarizada y estructurada.</p>','ordinario',1,'Disposiciones','Capítulo I · Disposiciones generales',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('08e9bacf-ccbb-5213-ba13-59969bfc28f9'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 2','<p>Artículo 2.- La presente Norma es de observancia obligatoria para las Unidades del Estado integrantes del SNIEG que generan Información de Interés Nacional o que sirva para generar esta, ya sea realizada por sí mismas o a través de terceros, cuando estas les encomienden dicha actividad. El Instituto deberá observar la presente Norma en todos sus Procesos de Producción.</p>','ordinario',2,'Disposiciones','Capítulo I · Disposiciones generales',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('38b8dd1d-ff58-5591-b876-8ccdc8b8e05b'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 3','<p>Artículo 3.- Para efectos de la presente Norma, se entenderá por:</p>
<p>I. Atributo: concepto que proporciona elementos cualitativos sobre las propiedades y características de un objeto específico;</p>
<p>II. Conjunto de datos: datos organizados. Incluyen Metadatos Estructurales a través de los cuales estos datos se vinculan entre sí y se agrupan dentro de una misma unidad temática;</p>
<p>III. DGIAI: Dirección General de Integración, Análisis e Investigación del Instituto Nacional de Estadística y Geografía;</p>
<p>IV. Dimensiones: combinación de conceptos que se utilizan para identificar y distinguir las observaciones individuales de un conjunto de datos;</p>
<p>V. Información de Interés Nacional o IIN: información que se determine como tal, en términos de lo dispuesto en los artículos 77 fracción II, y 78 de la Ley del Sistema Nacional de Información Estadística y Geográfica;</p>
<p>VI. Información Estadística: conjunto de resultados cuantitativos o datos que se obtienen de las Actividades Estadísticas y Geográficas en materia estadística, tomando como base los datos primarios obtenidos de los Informantes del Sistema sobre hechos que son relevantes para el conocimiento de los fenómenos económicos, gobierno, seguridad pública e impartición de justicia; demográficos y sociales, así como sus relaciones con el medio ambiente y el espacio territorial;</p>
<p>VII. Información Geográfica o Geoespacial: conjunto organizado de datos espaciales georreferenciados que mediante símbolos y códigos genera el conocimiento acerca de las condiciones físico-ambientales de los recursos naturales y de las obras de naturaleza antrópica del territorio nacional;</p>
<p>VIII. Informantes del Sistema: a las personas físicas y morales, a quienes les sean solicitados datos estadísticos y geográficos en términos de la Ley del SNIEG;</p>
<p>IX. Infraestructura de Información: conjunto de datos y metodologías que soportan el proceso de producción de información para facilitar su interoperabilidad. Se compone de catálogos y clasificaciones; registros estadísticos y geográficos; y metodologías;</p>
<p>X. Instituto o INEGI: Instituto Nacional de Estadística y Geografía;</p>
<p>XI. Metadatos: datos estructurados que describen las características de contenido, captura, procesamiento, calidad, condición, acceso y distribución de la información estadística o geográfica;</p>
<p>XII. Metadatos Descriptivos: datos que permiten la identificación y caracterización de documentos técnicos y conceptuales que dan soporte a los Procesos de Producción;</p>
<p>XIII. Metadatos Estructurales: datos que reconocen y especifican los atributos, dimensiones y medidas de los conjuntos de datos, actuando como identificadores y descriptores de los mismos;</p>
<p>XIV. Metadatos Referenciales: datos sobre la descripción de los conceptos, metodologías aplicadas, métodos utilizados y dimensiones de calidad asociadas a la producción y/o actualización de la información;</p>
<p>XV. Microdatos: valores de las variables asociadas a cada una de las Unidades de Observación;</p>
<p>XVI. Necesidad Estructurada de Información: necesidad de información para la que se han definido el objetivo de la información, los conceptos a ser medidos, la población, territorio o fenómeno objeto de estudio, los dominios de estudio y la periodicidad con la que se requiere;</p>
<p>XVII. Norma Técnica o Norma: Norma Técnica para la elaboración de Metadatos de los Procesos de Producción de Información Estadística y Geográfica;</p>
<p>XVIII. Proceso de Producción: conjunto de actividades, recursos, datos e infraestructura de información y fases que se relacionan lógicamente y ejecutan para producir información que permita alcanzar los objetivos y metas definidos por el Programa de Información que le da origen;</p>
<p>XIX. Producto: información que resulta de la ejecución de los procesos de producción que atienden necesidades estructuradas de información. Un Producto está asociado a uno o más dominios de estudio y conceptos de interés, organizados en un conjunto de presentaciones y servicios para las y los usuarios;</p>
<p>XX. Programa de Información: conjunto de actividades mediante el cual se establecen los objetivos, metas y estrategias para la ejecución de uno o más Procesos de Producción para atender Necesidades Estructuradas de Información, de las cuales podrán resultar uno o más productos estadísticos y geográficos;</p>
<p>XXI. Sistema Integrador de Metadatos o SIM: herramienta informática desarrollada por el INEGI y administrada por la DGIAI para la gestión de los metadatos de la información estadística y geográfica, haciendo uso de un grupo de módulos que permiten su captura, edición, revisión, validación y difusión;</p>
<p>XXII. Sistema Nacional de Información Estadística y Geográfica o SNIEG: conjunto de Unidades organizadas a través de los Subsistemas, coordinadas por el Instituto y articuladas mediante la Red Nacional de Información, con el propósito de producir y difundir la Información de Interés Nacional;</p>
<p>XXIII. Subsistemas Nacionales de Información o Subsistemas: componentes del Sistema enfocados a producir información de una determinada clase o respecto de temas específicos, y</p>
<p>XXIV. Unidades del Estado o UE: áreas administrativas que cuenten con atribuciones para desarrollar Actividades Estadísticas y Geográficas o que cuenten con registros administrativos que permitan obtener Información de Interés Nacional de:</p>
<p>a) Las dependencias y entidades de la Administración Pública Federal, incluyendo a las de la Presidencia de la República;</p>
<p>b) Los poderes Legislativo y Judicial de la Federación;</p>
<p>c) Las entidades federativas, los municipios y las demarcaciones territoriales de la Ciudad de México;</p>
<p>d) Los organismos constitucionales autónomos, y</p>
<p>e) Los tribunales administrativos federales. Cuando el Instituto genere IIN se considerará como Unidad del Estado para efectos de la Ley del SNIEG.</p>','ordinario',3,'Disposiciones','Capítulo I · Disposiciones generales',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('474ba2bc-f1c9-5a10-92a5-252a53547b48'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 4','<p>Artículo 4.- Las UE deberán documentar o actualizar los aspectos conceptuales, metodológicos, operativos y de calidad de los Procesos de Producción de información estadística y geográfica, de acuerdo con los elementos de Metadatos Referenciales establecidos en el Instrumento complementario denominado Anexo I de esta disposición normativa.</p>','ordinario',4,'Disposiciones','Capítulo II · Disposiciones específicas',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('276b9424-de80-5c3e-aa93-63aee358ded7'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 5','<p>Artículo 5.- Las UE deberán documentar o actualizar los atributos, dimensiones y medidas de los conjuntos de datos resultantes de los Procesos de Producción de información estadística y geográfica, de acuerdo con los de Metadatos Estructurales establecidos en el Instrumento complementario denominado Anexo II de esta disposición normativa.</p>','ordinario',5,'Disposiciones','Capítulo II · Disposiciones específicas',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('70ade02d-8b37-5202-98cb-dccb493c7c5c'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 6','<p>Artículo 6.- Las UE deberán documentar o actualizar los metadatos de los documentos técnicos y conceptuales que dan soporte a los Procesos de Producción de información estadística y geográfica, de acuerdo con los elementos de Metadatos Descriptivos establecidos en el Instrumento complementario denominado Anexo III de la presente disposición normativa.</p>','ordinario',6,'Disposiciones','Capítulo II · Disposiciones específicas',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('c5bac96f-50a8-5408-a761-4e8704147976'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 7','<p>Artículo 7.- Las UE deberán llevar a cabo la documentación o actualización de los metadatos a los que hacen referencia los artículos 4, 5 y 6 de acuerdo con la Guía para la implementación de la Norma Técnica para la elaboración de Metadatos de los Procesos de Producción de Información Estadística y Geográfica, disponible en el Sistema de Compilación Normativa del SNIEG. La Guía será integrada y actualizada por la DGIAI en correspondencia con las revisiones a las especificaciones de metadatos que se mencionan en el artículo 8 de esta Norma.</p>','ordinario',7,'Disposiciones','Capítulo II · Disposiciones específicas',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('15559104-e31a-5ad4-a497-8f3af615d077'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 8','<p>Articulo 8.- Las especificaciones de metadatos referidos en los artículos 4, 5 y 6 de la presente Norma Técnica serán revisadas por la DGIAI del Instituto, según se requiera, en colaboración con las Unidades del Estado que tengan competencia en el tema. En caso de ser necesaria alguna modificación, la DGIAI solicitará, mediante comunicación oficial, a la Dirección General de Coordinación del Sistema Nacional de Información Estadística y Geográfica su actualización en el Sistema de Compilación Normativa ubicado en el Portal del SNIEG.</p>','ordinario',8,'Disposiciones','Capítulo II · Disposiciones específicas',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('da553d4a-9223-55bc-875b-78af56f1a689'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 9','<p>Artículo 9.- Las UE deberán actualizar los metadatos que requieran ser revisados o complementados de acuerdo con cada ciclo ejecutado de los Procesos de Producción de información estadística y geográfica.</p>','ordinario',9,'Disposiciones','Capítulo III · Implementación de la Norma Técnica',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('b08295d6-63fa-5419-a7cc-16414cb6eaba'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 10','<p>Artículo 10.- Las UE deberán realizar la documentación o actualización de los metadatos mediante el Sistema Integrador de Metadatos (SIM) desarrollado por el INEGI, administrado por la DGIAI, disponible a través del Portal del SNIEG.</p>','ordinario',10,'Disposiciones','Capítulo III · Implementación de la Norma Técnica',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('dc12f091-c628-5bbf-9bb0-070b1995f2a7'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 11','<p>Artículo 11.- En un plazo no mayor a 10 días hábiles, a partir de la notificación de conclusión de la documentación de metadatos, la DGIAI verificará el cumplimiento de las especificaciones indicadas en los artículos 4, 5 y 6. La DGIAI notificará por escrito el resultado a la UE para la atención de las observaciones en correspondencia con la fecha de publicación comprometida en el Calendario de Información de Interés Nacional y en el Calendario de difusión de información estadística, geográfica y de Interés Nacional del INEGI, según corresponda.</p>','ordinario',11,'Disposiciones','Capítulo III · Implementación de la Norma Técnica',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('6dd06024-fec1-5c45-90d1-a10846109a07'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 12','<p>Artículo 12.- Una vez atendidas las observaciones, la UE deberá autorizar, con al menos 24 horas de anticipación a la fecha prevista para su publicación, la publicación de los metadatos de los Procesos de Producción correspondientes a través del SIM.</p>','ordinario',12,'Disposiciones','Capítulo III · Implementación de la Norma Técnica',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('8c563021-ae01-5288-b43c-84d90ddf6916'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 13','<p>Artículo 13.- La publicación de los metadatos de los Procesos de Producción de información estadística y geográfica documentados o actualizados de acuerdo con las disposiciones establecidas en la presente Norma Técnica, se realizará a través del Sistema de Difusión de Metadatos del SIM que será parte del Portal del INEGI.</p>
<p>Los metadatos de los Procesos de Producción deberán publicarse junto con los productos correspondientes, de acuerdo con las fechas comprometidas en el Calendario de Información de Interés Nacional y en el Calendario de difusión de información estadística, geográfica y de Interés Nacional del INEGI, según corresponda.</p>','ordinario',13,'Disposiciones','Capítulo III · Implementación de la Norma Técnica',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('17f57406-2d87-5a6b-b40a-670fe04abcdc'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 14','<p>Artículo 14.- Para el acceso al módulo de captura y edición de metadatos del SIM, la DGIAI integrará y mantendrá actualizado el directorio de personas servidoras públicas responsables de la captura y autorización de metadatos. Para la conformación y actualización del referido directorio, la DGIAI solicitará por escrito a las UE las designaciones de las personas servidoras públicas que serán responsables de la captura y autorización de metadatos. Las UE notificarán por escrito a la DGIAI sobre cualquier cambio en la designación de personas servidoras públicas responsables de la captura y autorización de metadatos.</p>','ordinario',14,'Disposiciones','Capítulo III · Implementación de la Norma Técnica',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('452eb9c7-f7ba-5a42-b13e-f3454ff34179'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 15','<p>Artículo 15.- La DGIAI impartirá la capacitación sobre la operación del módulo de captura y edición de metadatos del SIM a las personas servidoras públicas responsables de la captura y autorización de metadatos.</p>','ordinario',15,'Disposiciones','Capítulo III · Implementación de la Norma Técnica',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('e08173a4-ef04-5380-bece-5ef9f31a3be0'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Artículo 16','<p>Artículo 16.- La vigilancia del cumplimiento e interpretación de la presente Norma Técnica para efectos administrativos y técnicos corresponderá a la persona titular de la DGIAI del Instituto, la cual deberá resolver los casos no previstos por la misma y propondrá su actualización ante las instancias competentes, en términos del marco legal correspondiente.</p>','ordinario',16,'Disposiciones','Capítulo IV · Vigilancia e interpretación',null) on conflict (id) do nothing;
insert into public.articulos (id,ley_id,identificador,contenido,tipo_articulo,orden,titulo_nombre,capitulo_nombre,seccion_nombre) values ('4964d7da-beb7-52c8-8159-9dad51c84241'::uuid,'75653b58-109e-52bb-970c-72041a77b06a'::uuid,'Transitorios','<p>TRANSITORIOS</p>
<p>PRIMERO.- La presente Norma Técnica para la elaboración de Metadatos de los Procesos de Producción de Información Estadística y Geográfica entrará en vigor al día siguiente de su publicación en el Diario Oficial de la Federación.</p>
<p>SEGUNDO.- Se abroga la Norma Técnica para la Elaboración de Metadatos para proyectos de generación de Información Estadística Básica y de los componentes estadísticos derivados de proyectos geográficos, aprobada mediante Acuerdo 5ª/III/2015, en la Quinta sesión de 2015 de la Junta de Gobierno del Instituto Nacional de Estadística y Geografía, publicada en el Diario Oficial de la Federación el 3 de septiembre de 2015, así como las herramientas para la documentación de los metadatos de dicha disposición normativa.</p>
<p>TERCERO. - Los Instrumentos complementarios a que hacen referencia los artículos 4, 5, 6 y 10 de esta Norma Técnica, estarán disponibles en el Portal del SNIEG una vez que la Norma se publique en dicho sitio.</p>
<p>CUARTO. - La integración del directorio de personas servidoras públicas responsables de la captura y autorización de metadatos referido en el primer párrafo del artículo 14 de esta Norma Técnica, deberá realizarse en un plazo no mayor de 6 meses contados a partir de la entrada en vigor de la presente Norma Técnica.</p>
<p>QUINTO. - Para dar cumplimiento al artículo 15 de esta disposición normativa, la DGIAI capacitará a las UE a las que hace referencia el artículo 2 de esta Norma Técnica en un plazo no mayor de 9 meses contados a partir de su entrada en vigor.</p>
<p>SEXTO. - Las UE a las que hace referencia el artículo 2 de esta Norma Técnica deberán adoptar las disposiciones de la presente Norma, mediante el SIM, en un plazo no mayor de 12 meses contados a partir de la conclusión del periodo de capacitación al que hace referencia el artículo quinto transitorio de la presente Norma Técnica.</p>
<p>SÉPTIMO. - Los metadatos elaborados o en proceso de elaboración según las disposiciones de la Norma Técnica para la Elaboración de Metadatos para proyectos de generación de Información Estadística Básica y de los componentes estadísticos derivados de proyectos geográficos, serán migrados por la DGIAI al Sistema de Difusión de Metadatos del SIM en un plazo no mayor de un año contado a partir de su entrada en vigor. La Norma Técnica para la elaboración de Metadatos de los Procesos de Producción de Información Estadística y Geográfica se aprobó en términos del Acuerdo 12ª/VI/2025, aprobado en la Décima Segunda sesión de 2025, de la Junta de Gobierno del Instituto Nacional de Estadística y Geografía, celebrada el 1.º de septiembre de 2025.- Presidenta: Graciela Márquez Colín.- Vicepresidentes: Adrián Franco Barrios, Mauricio Márquez Corona, José Arturo Blancas Espejo y Rosa Isabel Islas Arredondo. Aguascalientes, Ags., a 1° de septiembre de 2025.- Hace constar lo anterior el Director General de Asuntos Jurídicos, Jorge Ventura Nevares, en ejercicio de la atribución que le confiere lo dispuesto en la fracción V, del artículo 52 del Reglamento Interior del Instituto Nacional de Estadística y Geografía.- Rúbrica.</p>','transitorio',17,'Transitorios',null,null) on conflict (id) do nothing;
update public.articulos set contenido = replace(contenido, E'\r\n', E'\n') where ley_id = '75653b58-109e-52bb-970c-72041a77b06a'::uuid;
commit;
