import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
const dir=new URL('.',import.meta.url),map=JSON.parse(readFileSync(new URL('map.json',dir),'utf8'));
const pack=JSON.parse(readFileSync(new URL('articulos-verificados.json',dir),'utf8')),audit=JSON.parse(readFileSync(new URL('cotejo.json',dir),'utf8'));
const path=new URL('../../public/reader-sources/manifest.v1.json',dir);let raw=readFileSync(path,'utf8');const manifest=JSON.parse(raw),articles=pack.articulos,expected=new Map(articles.map(a=>[a.id,a]));
const sha='82f15ac85c7de97078a578dd5e5ac6ef2c5025d6f7af9d1a9a398a5a58b56787';
if(pack.ley.id!=='1a4e15a0-cb72-4195-9d96-fe1d939db0e2'||map.source.originalUrl!=='https://sidof.segob.gob.mx/notas/getNewsletter/17-10-2025/Vespertina/323603'||map.source.id!==`dof-vespertina-2025-10-17-${sha.slice(0,12)}`||map.source.sha256!==sha||map.source.pageCount!==134||articles.length!==11||Object.keys(map.articles).length!==11||Object.keys(map.articles).some(id=>!expected.has(id))||audit.paginasImpresasDelInstrumento.join(',')!=='113,116')throw new Error('El cotejo no cubre los once fragmentos oficiales.');
for(const[id,e]of Object.entries(map.articles)){const a=expected.get(id);if(e.sourceId!==map.source.id||e.label!==a.identificador||e.type!==a.tipo_articulo||e.contentSha256!==createHash('sha256').update(a.contenido,'utf8').digest('hex')||!e.anchors.length||e.pageNumbers.some(n=>n<113||n>116))throw new Error(`Cotejo incompleto: ${a.identificador}`);for(const x of e.anchors){const p=map.source.pages.find(v=>v.number===x.page),[x0,y0,x1,y1]=x.bbox;if(!p||![x0,y0,x1,y1].every(Number.isFinite)||!(0<=x0&&x0<x1&&x1<=p.width&&0<=y0&&y0<y1&&y1<=p.height))throw new Error(`Coordenada inválida: ${a.identificador}`);}}
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),old=manifest.sources[map.source.id];if(old&&!same(old,map.source))throw new Error('La edición ya está registrada con otra huella.');const prior=Object.fromEntries(Object.entries(manifest.articles).filter(([,e])=>e.sourceId===map.source.id));if(Object.keys(prior).length&&!same(prior,map.articles))throw new Error('Existe un mapa parcial diferente.');for(const[id,e]of Object.entries(map.articles))if(manifest.articles[id]&&!same(manifest.articles[id],e))throw new Error(`Mapa distinto para ${id}.`);
const sources=old?{}:{[map.source.id]:map.source},newMaps=Object.fromEntries(Object.entries(map.articles).filter(([id])=>!manifest.articles[id]));if(!Object.keys(sources).length&&!Object.keys(newMaps).length)console.log('Los once mapas ya están publicados.');else{const eol=raw.includes('\r\n')?'\r\n':'\n',indent=v=>JSON.stringify(v,null,2).split('\n').map((s,i)=>i?`  ${s}`:s).join(eol);if(Object.keys(sources).length){const b=`${eol}  },${eol}  "articles": {`;if(!raw.includes(b))throw new Error('Cierre de sources no encontrado.');const rows=Object.entries(sources).map(([id,v])=>`    ${JSON.stringify(id)}: ${indent(v)}`).join(`,${eol}`);raw=raw.replace(b,`,${eol}${rows}${eol}  },${eol}  "articles": {`);}if(Object.keys(newMaps).length){const b=/\r?\n  }\r?\n}\r?\n?$/;if(!b.test(raw))throw new Error('Cierre de articles no encontrado.');const rows=Object.entries(newMaps).map(([id,v])=>`    ${JSON.stringify(id)}: ${indent(v)}`).join(`,${eol}`);raw=raw.replace(b,`,${eol}${rows}${eol}  }${eol}}`);}raw=raw.replace(`"revision": ${manifest.revision}`,`"revision": ${manifest.revision+1}`).replace(/("verifiedAt":\s*)"[^"]+"/,(_,p)=>`${p}"${new Date().toISOString()}"`);JSON.parse(raw);writeFileSync(path,raw);console.log(`Manifiesto ${manifest.revision} → ${manifest.revision+1}; ${Object.keys(newMaps).length} mapas agregados.`);}
