"""Genera el informe de hallazgos confirmados; no contiene funciones de escritura remota."""
from pathlib import Path
import json,re,html,csv,unicodedata,collections
root=Path(__file__).resolve().parent
load=lambda f:json.loads((root/f).read_text(encoding='utf8'))
articles=load('supabase-articulos.json');laws=load('supabase-leyes.json');sources=load('fuentes.json');auto=load('analisis-automatico.json');checked=load('cotejo.json')
byid={a['id']:a for a in articles}
def norm(s):return re.sub('[^a-z0-9]','',unicodedata.normalize('NFD',s.lower()))
def excerpt(text,needle=''):
    chars=[];positions=[]
    for i,c in enumerate(text):
        for k in norm(c):chars.append(k);positions.append(i)
    at=''.join(chars).find(norm(needle)[:45]) if needle else -1
    if at>=0:
        p=positions[at];return ('…' if p>100 else '')+text[max(0,p-100):p+750]+('…' if p+750<len(text) else '')
    return text if len(text)<900 else text[:600]+'\n[…]\n'+text[-230:]
config=[
('RLSE','Cortes confirmados','16 artículos carecen de identificación correcta: 12 están unidos a otros y 4 tienen el número truncado. El transitorio Octavo también fue cortado por una referencia al Noveno.',[32,45,58,71,74,77,79,123,134,185,207,208,265,272,287,294]),
('LSE','Cortes confirmados','Seis artículos están unidos al anterior. Se mezclaron transitorios de la ley y del decreto y se creó un falso transitorio con una referencia a otros artículos del decreto.',[13,43,45,76,86,114]),
('LPTE','Cortes confirmados','Los artículos 14 y 66 están unidos al anterior. Se mezclaron transitorios de la ley y del decreto y se creó un falso transitorio con una referencia del decreto.',[14,66]),
('LGTAIP','Cortes confirmados','Cuatro artículos están unidos al anterior. El transitorio Décimo Quinto fue partido por una referencia interna y el Décimo Séptimo quedó mal identificado.',[54,86,138,158]),
('LGEC','Cortes confirmados','El artículo 44 está dentro del 43. La fecha de publicación almacenada también es incorrecta.',[44]),
('PODECOBI-LIN','Cortes confirmados','Los lineamientos 9 y 16 quedaron dentro del preámbulo; 13 y 14 dentro del lineamiento 12. Hay 35 fragmentos ordinarios para 39 lineamientos.',[]),
('SAEE','Cortes confirmados','El numeral 3.13 fue cortado al citar 3.12, creando un segundo fragmento etiquetado 3.12. Hay pies de impresión dentro del texto.',[]),
('RLSH','Cortes confirmados','Los 336 artículos tienen identificación individual. Dos referencias dentro de transitorios se convirtieron en fragmentos adicionales: Tercero y Artículo Transitorio.',[]),
('PODECOBI-DEC','Cortes confirmados','Una referencia al artículo 89 constitucional se convirtió en un artículo del decreto. El decreto tiene 13 artículos ordinales, además de 3 transitorios.',[]),
('DACG-PV','Limpieza y metadatos','Los 8 artículos y el transitorio único están identificados. Hay pies de impresión y fecha de publicación incorrecta.',[]),
('RISENER','Limpieza y metadatos','Los 78 artículos y 7 transitorios están identificados, además de la fórmula de expedición. La fecha guardada corresponde a la firma y no a la publicación; el cierre está unido al último transitorio.',[]),
('RLPTE','Limpieza y metadatos','Los 136 artículos y 13 transitorios están identificados, además de la fórmula de expedición. No se confirmaron fusiones o falsos cortes de disposiciones; hay encabezados y firmas unidos al cuerpo de fragmentos.',[]),
]
extra={
'RLSE': [('Corte falso dentro del Octavo','671132d4-7f16-4622-910a-18a90832cc79','La frase «de la Ley emita la Secretaría» continúa la referencia al transitorio Noveno dentro del Octavo; no es otro transitorio.')],
'LSE':[('Referencia del decreto tratada como transitorio','6096d529-6164-497e-8229-6f32b936e2df','ARTÍCULO CUARTO A ARTÍCULO DÉCIMO es material del decreto, no una disposición transitoria de la ley.')],
'LPTE':[('Referencia del decreto tratada como transitorio','b24e7517-7c92-4829-8a99-a8ac81479459','ARTÍCULO SEXTO A ARTÍCULO DÉCIMO es material del decreto, no una disposición transitoria de la ley.')],
'LGTAIP':[('Corte falso del Décimo Quinto','d574ce36-1a91-48f5-8bfd-0ce28b0e8103','Este texto continúa el transitorio Décimo Quinto después de la referencia a Décimo Tercero.'),('Décimo Séptimo mal identificado','aeb089ab-04ef-4c9c-860e-ce2cbf77c947','El contenido empieza «Sé ptimo. -» y completa el ordinal Décimo Séptimo; no es otro Décimo.')],
'SAEE':[('3.13 partido por su referencia a 3.12','6b1e977c-ba0e-4e78-b396-68776945925c','Debe continuar el numeral 3.13 (UUID 89994faa-472c-45f2-88f9-0b6516162225). El auténtico 3.12 tiene UUID 398c21fe-8157-4b80-8a8e-fafaf6335ded.')],
'RLSH':[('Corte falso del Segundo','3961528a-0292-47c4-a5b2-9cf99d653261','Continúa «Reglamento de las Actividades a que se refiere el Título Tercero de la Ley de Hidrocarburos» dentro del Segundo.'),('Corte falso del Décimo Segundo','40752873-fa9e-4dd2-a872-6f4ae0f382c3','La frase «del presente artículo transitorio deben cumplir…» pertenece al Décimo Segundo, no constituye otro transitorio.')],
'PODECOBI-DEC':[('Artículo 89 constitucional confundido con artículo del decreto',None,'El encabezado del decreto contiene la referencia a la facultad constitucional. El texto anterior a Artículo Primero forma parte del preámbulo.')]
}
reports=[]
for name,status,summary,missing in config:
    source=next(x for x in sources if x['name']==name);law=next(x for x in laws if x['id']==source['ley_id']);stats=next(x for x in auto if x['name']==name);cotejo=next(x for x in checked if x['name']==name)
    db=sorted([x for x in articles if x['ley_id']==law['id']],key=lambda x:x['orden']);candidates=load(f'fuentes/{name}.candidatos.json')['chunks'];evidence=[]
    for num in missing:
        unit=next(x for x in cotejo['missing_standalone'] if x['num']==num)
        target=unit['matches'][0]['id'] if unit['matches'] else {'RLSE':{207:'fbe38f85-3438-41d0-9640-afa875d1b504'},'LPTE':{14:'73cbbf7b-81d2-4838-9781-50e685395c47'}}[name][num]
        a=byid[target]
        expected={'RLSE':{32:3,45:4,123:12,207:206,208:206,287:2}}.get(name,{}).get(num,num-1)
        assert int(re.search(r'\d+',a['identificador'])[0])==expected,(name,num,a['identificador'])
        evidence.append({'hallazgo':f'Artículo {num} sin fragmento correctamente identificado','id':target,'etiqueta_bd':a['identificador'],'orden_bd':a['orden'],'texto_bd':excerpt(a['contenido'],unit['source_start']),'texto_fuente':unit['source_start'],'accion':'Restituir la identidad y los límites del artículo cotejando todo su contenido.'})
    if name=='PODECOBI-LIN':
        for num in [9,13,14,16]:
            c=next(x for x in candidates if x['identificador']==f'Numeral {num}');needle=norm(c['contenido'])[:60];a=next(x for x in db if needle in norm(x['contenido']))
            evidence.append({'hallazgo':f'Lineamiento {num} en otro fragmento','id':a['id'],'etiqueta_bd':a['identificador'],'orden_bd':a['orden'],'texto_bd':excerpt(a['contenido'],c['contenido']),'texto_fuente':c['contenido'],'accion':'Crear un fragmento propio y retirar su texto del fragmento que lo absorbió.'})
    for label,id,explanation in extra.get(name,[]):
        a=byid[id] if id else next(x for x in db if norm(x['identificador'])=='articulo89')
        evidence.append({'hallazgo':label,'id':a['id'],'etiqueta_bd':a['identificador'],'orden_bd':a['orden'],'texto_bd':excerpt(a['contenido']),'texto_fuente':explanation,'accion':'Reunir o reclasificar el texto con su disposición de origen. Preservar la trazabilidad del UUID actual.'})
    if name in ['LSE','LPTE']:
        trans=[x for x in db if x['tipo_articulo']=='transitorio' and re.search(r'PRIMERO',x['identificador'])]
        evidence.append({'hallazgo':'Dos bloques de transitorios comparten etiqueta','id':trans[-1]['id'],'etiqueta_bd':trans[-1]['identificador'],'orden_bd':trans[-1]['orden'],'texto_bd':excerpt(trans[-1]['contenido']),'texto_fuente':'La ley y el decreto de expedición tienen bloques propios. Deben conservarse y distinguirse, sin tratarlos como dos versiones del mismo artículo.','accion':'Separar los bloques y sus metadatos de pertenencia.'})
    if name in ['DACG-PV','RISENER','LGEC']:
        d,m,y=source['fecha'].split('-');date=f'{y}-{m}-{d}'
        evidence.append({'hallazgo':'Fecha de publicación incorrecta','id':law['id'],'etiqueta_bd':'leyes.fecha_publicacion','texto_bd':law['fecha_publicacion'],'texto_fuente':date,'accion':'Corregir la fecha bibliográfica a partir de la publicación oficial; conservar separada la fecha de firma si se necesita.'})
    if name in ['RISENER','RLPTE','DACG-PV']:
        a=db[-1];evidence.append({'hallazgo':'Firmas o pie editorial dentro del último transitorio','id':a['id'],'etiqueta_bd':a['identificador'],'orden_bd':a['orden'],'texto_bd':a['contenido'][-700:],'texto_fuente':'El cierre del decreto y las firmas son material documental separado de la disposición transitoria.','accion':'Separar el cierre y revisar el pie de impresión, conservando el texto normativo.'})
    # Marcadores inequívocos de un pie editorial o de la impresión web; son un indicador, no una revisión tipográfica exhaustiva.
    noise=[x['id'] for x in db if 'secretariadeserviciosparlamentarios' in norm(x['contenido']) or 'print=true' in x['contenido']]
    reports.append({'instrumento':name,'titulo':law['titulo'],'ley_id':law['id'],'estado':status,'resumen':summary,'fragmentos':len(db),'temas':stats['themes'],'con_jerarquia':stats['with_hierarchy'],'fragmentos_con_marcadores_editoriales':noise,'fuente':source['url'],'fuente_local':f'fuentes/{name}.pdf' if source['format']=='pdf' else f'fuentes/{name}.html','evidencias':evidence})
assert len(reports)==12 and len(articles)==1749
assert sum(r['estado']=='Cortes confirmados' for r in reports)==9
assert sum(len([e for e in r['evidencias'] if e['hallazgo'].startswith(('Artículo ','Lineamiento ')) and 'constitucional' not in e['hallazgo']])for r in reports)==33
result={'fecha':load('snapshot.json')['fecha'],'solo_lectura':True,'alcance':'Revisión estructural de todas las filas y cotejo focalizado con fuentes oficiales; no certifica cada carácter ni vigencia jurídica.','instrumentos':reports}
(root/'hallazgos-confirmados.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf8')
md=['# Auditoría del acervo cargado — 17 de septiembre de 2026','','**12 instrumentos y 1,749 fragmentos examinados. Nueve instrumentos tienen errores de fragmentación confirmados; los otros tres requieren limpieza o metadatos. No se modificó Supabase.**','','Hay 33 artículos o numerales sin un fragmento correctamente identificado: 29 están unidos o desplazados a otro fragmento y 4 están rotulados con el número truncado. El texto localizado en otro fragmento no se considera perdido. Además hay referencias internas convertidas en disposiciones, bloques de transitorios mezclados y tres fechas incorrectas.','','| Instrumento | Fragmentos | Resultado |','|---|---:|---|']
for r in reports:md.append(f"| {r['instrumento']} | {r['fragmentos']} | {r['resumen']} |")
md+=['','## Cómo se comprobó','','Se exportaron únicamente leyes, artículos y temas con lectura pública paginada y conteos exactos. La fotografía guarda los UUID actuales y un hash. Se comprobaron secuencias, identificadores, tipos, orden, texto vacío y marcadores editoriales. No hay contenido, identificadores ni índices FTS nulos/vacíos en las 1,749 filas consultadas; tampoco órdenes duplicados por instrumento. Eso no garantiza una fragmentación correcta.','','Se descargaron las 12 fuentes oficiales enlazadas por el catálogo. Para LSE, el enlace devuelve el decreto completo de 258 páginas: el cotejo se delimitó a su ley, entre los artículos de expedición Tercero y Cuarto. Para LGEC se distinguieron las reformas a otras leyes incluidas en el mismo decreto. Se guardaron fuentes, hashes, extracción y resultados por fila.','','El parser nuevo se utilizó solo para localizar candidatos: no se tomó su resultado como verdad jurídica ni como reemplazo automático. También presenta diferencias y falsos positivos en algunas fuentes; cada reparación debe cotejarse. Se confirmaron los casos señalados con el texto almacenado y la fuente. Se inspeccionaron visualmente las páginas 12 del RLSE y 8 de LPTE.','','La auditoría cubre estructura y fallos encontrados; no es una certificación tipográfica integral, de todas las tablas, ni una revisión de vigencia. Las diferencias de signos o de longitud del análisis automático no se clasificaron por sí solas como pérdida de texto.','','Ocho instrumentos carecen de filas en `temas`; seis de ellos sí tienen estructura relevante en su fuente. Esto se registra aparte de los errores de corte. Algunos artículos conservan jerarquía aunque falte la tabla de temas.','']
for r in reports:
    md += [f"## {r['instrumento']} — {r['estado']}",'',r['titulo'],'',r['resumen'],'',f"[Fuente oficial]({r['fuente']}) · UUID del instrumento: `{r['ley_id']}`",'']
    for e in r['evidencias']:
        md += [f"### {e['hallazgo']}",'',f"Registro: `{e['id']}` · Etiqueta actual: **{e['etiqueta_bd']}**",'', 'Texto almacenado (extracto):','', '```text',e['texto_bd'],'```','','Fuente o explicación del cotejo:','',e['texto_fuente'],'',f"Acción pendiente: {e['accion']}",'']
md += ['## Orden propuesto de reparación','','1. RLSE, por la cantidad de artículos mal identificados o fusionados.','2. LSE, LPTE, LGTAIP y LGEC: restituir artículos y separar transitorios.','3. PODECOBI lineamientos, SAEE, RLSH y decreto PODECOBI: corregir los falsos cortes identificados.','4. Fechas, pies de impresión, firmas e índices temáticos de todos los instrumentos.','','Reparar un instrumento a la vez, con un diff revisable y cotejo de todo el texto afectado. Conservar los UUID de artículos que siguen representando la misma disposición y resolver explícitamente los enlaces, notas y favoritos cuando haya fusiones o nuevos artículos. No borrar y recargar masivamente. El guardado actual no es transaccional; una reparación debe prever recuperación de fallos.','','## Archivos','','- `hallazgos-confirmados.json`: evidencias y UUID para preparar reparaciones.','- `AUDITORIA.html`: informe navegable.','- `supabase-*.json` y `snapshot.json`: copia íntegra de lectura, con conteos y hash.','- `fuentes/`: originales oficiales y extracción.','- `analisis-automatico.json` y `cotejo.json`: indicadores por fila; incluyen alertas que no equivalen a errores confirmados.']
(root/'AUDITORIA.md').write_text('\n'.join(md),encoding='utf8')
with (root/'resumen.csv').open('w',encoding='utf-8-sig',newline='') as f:
    w=csv.writer(f);w.writerow(['instrumento','estado','fragmentos','temas','resumen','fuente','ley_id']);w.writerows([[r[k] for k in ['instrumento','estado','fragmentos','temas','resumen','fuente','ley_id']]for r in reports])
esc=html.escape
cards=[]
for r in reports:
    ev=''.join(f'''<details><summary>{esc(e['hallazgo'])}</summary><p class="meta">Etiqueta: {esc(e['etiqueta_bd'])}<br>UUID: <code>{e['id']}</code></p><div class="compare"><section><h4>Almacenado</h4><pre>{esc(e['texto_bd'])}</pre></section><section><h4>Fuente / comprobación</h4><pre>{esc(e['texto_fuente'])}</pre></section></div><p><b>Reparación pendiente:</b> {esc(e['accion'])}</p></details>'''for e in r['evidencias'])
    cards.append(f'''<article data-status="{esc(r['estado'])}" id="{r['instrumento']}"><header><h2>{r['instrumento']}</h2><span class="badge {'high' if r['estado']=='Cortes confirmados' else ''}">{r['estado']}</span></header><p class="name">{esc(r['titulo'])}</p><p>{esc(r['resumen'])}</p><p class="meta">{r['fragmentos']} fragmentos · {r['temas']} temas · {len(r['fragmentos_con_marcadores_editoriales'])} fragmentos con marcadores editoriales</p><p><a href="{esc(r['fuente'])}" target="_blank" rel="noopener">Fuente oficial ↗</a> · <a href="{r['fuente_local']}" target="_blank">Copia consultada</a></p>{ev}</article>''')
page='''<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Auditoría del acervo cargado</title><style>
:root{--wine:#832044;--ink:#26302c;--muted:#65716a}*{box-sizing:border-box}body{margin:0;background:#f4f5ef;color:var(--ink);font:15px/1.6 system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:32px 24px}h1{font:600 36px/1.2 Georgia,serif;max-width:850px}h2{margin:0;font-size:22px}.eyebrow{color:var(--wine);font-size:12px;font-weight:700;letter-spacing:.12em}a{color:var(--wine)}.stats{display:flex;flex-wrap:wrap;gap:20px;margin:26px 0}.stats div{background:white;border:1px solid #dde2da;padding:15px 24px;border-radius:10px}.stats b{display:block;font-size:28px}.notice{padding:16px 20px;border-left:4px solid #96732c;background:#f2ead7}.controls{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}input,select{padding:10px;border:1px solid #c9d1c6;border-radius:6px;font:inherit}input{flex:1;min-width:220px}article{background:white;padding:24px;margin:18px 0;border:1px solid #dde2da;border-radius:12px}article header{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.badge{font-size:12px;border-radius:20px;padding:5px 10px;background:#f2ead7;color:#6c5120}.badge.high{background:#f7e3e9;color:#832044}.name,.meta{color:var(--muted)}.meta{font-size:12px;overflow-wrap:anywhere}details{border-top:1px solid #e5e8e1;padding:14px 0}summary{cursor:pointer;font-weight:600}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.7 system-ui;background:#f6f7f2;padding:14px;border-radius:6px;margin:0}.compare{display:grid;grid-template-columns:1fr 1fr;gap:18px}h4{margin:10px 0;font-size:12px;text-transform:uppercase;letter-spacing:.06em}footer{color:var(--muted);font-size:13px;margin:30px 0}@media(max-width:650px){main{padding:20px 14px}h1{font-size:29px}.compare{grid-template-columns:1fr}article{padding:18px}.stats{gap:8px}.stats div{padding:10px 14px}}
</style><main><div class="eyebrow">ACERVO NORMATIVO · 17 SEPTIEMBRE 2026</div><h1>Sí hay errores de fragmentación en el acervo cargado.</h1><p>Auditoría de lectura contra las fuentes oficiales. Los hallazgos incluyen la etiqueta y el UUID actuales para preparar correcciones individuales.</p><div class="stats"><div><b>12</b>instrumentos revisados</div><div><b>1,749</b>fragmentos examinados</div><div><b>9</b>instrumentos con cortes incorrectos</div><div><b>0</b>cambios en Supabase</div></div><div class="notice"><b>El texto suele estar en otro fragmento.</b> Identificamos 33 artículos o numerales sin su identificación correcta: 29 unidos o desplazados y 4 con número truncado. No se debe borrar y volver a cargar todo el acervo. Esta auditoría es estructural; no certifica cada carácter, tabla o vigencia jurídica.</div><p><a href="AUDITORIA.md">Informe completo</a> · <a href="resumen.csv" download>Resumen CSV</a> · <a href="hallazgos-confirmados.json" download>Evidencia JSON</a></p><div class="controls"><input id="search" aria-label="Buscar instrumento o hallazgo" placeholder="Buscar instrumento, artículo o hallazgo"><select id="status" aria-label="Filtrar estado"><option value="">Todos los instrumentos</option><option>Cortes confirmados</option><option>Limpieza y metadatos</option></select></div><div id="cards">'''+''.join(cards)+'''</div><footer>Fuentes y copia completa del catálogo conservadas localmente. Se propone empezar por RLSE y avanzar un instrumento a la vez. Los análisis automáticos se usan como indicios; las diferencias de formato no se consideran por sí solas pérdida de contenido.</footer></main><script>const search=document.getElementById('search'),status=document.getElementById('status');function filter(){for(const c of document.querySelectorAll('article'))c.hidden=!!((status.value&&c.dataset.status!==status.value)||(search.value&&!c.textContent.toLocaleLowerCase('es').includes(search.value.toLocaleLowerCase('es'))))}search.oninput=filter;status.onchange=filter;</script></html>'''
if (root.parent/'reparacion-2026-09-17/VERIFICACION.json').exists():
    page=page.replace('<main>','<main><div class="notice"><b>Auditoría histórica anterior a la reparación.</b> Los 12 instrumentos ya fueron corregidos y verificados en Supabase. <a href="../reparacion-2026-09-17/CORRECCIONES.html">Ver el estado corregido</a>. El cotejo final confirmó 32 transitorios en RLSH; tres estaban unidos al Vigésimo Noveno.</div>',1)
    (root/'AUDITORIA.md').write_text('> **Estado posterior:** los 12 instrumentos fueron corregidos en Supabase. Ver [correcciones y verificación](../reparacion-2026-09-17/CORRECCIONES.md). Este informe conserva la fotografía anterior; el conteo de transitorios del RLSH se rectificó a 32.\n\n'+'\n'.join(md),encoding='utf8')
(root/'AUDITORIA.html').write_text(page,encoding='utf8')
print('Informe: 12 instrumentos, 9 con cortes confirmados, 33 unidades sin identidad correcta. Sin escrituras remotas.')
