from pathlib import Path
import json,html
R=Path(__file__).resolve().parent;load=lambda p:json.loads(p.read_text(encoding='utf8'));esc=html.escape
folders=[R,R.parent/'incorporacion-planeacion-2026-09-19',R.parent/'incorporacion-complementos-2026-09-19',R.parent/'incorporacion-cierre-prioridades-2026-09-19']
items=[]
for folder in folders:
 v=load(folder/'VERIFICACION.json');verified={x['ley_id']for x in v['instrumentos']if x['cotejo_exacto']}
 for m in load(folder/'sql-manifest.json'):
  p=load(folder/(m['name']+'-carga.json'));law=p['ley'];assert law['id']in verified
  items.append(dict(familia=p['fuente']['familia'],siglas=law['siglas'],titulo=law['titulo'],fecha=law['fecha_publicacion'],fragmentos=len(p['articulos']),url='https://buscador-leyes-jav.pages.dev/#ley-'+law['id'],fuente=law['url_original'],sha256=p['fuente']['sha256']))
assert len(items)==27 and sum(i['fragmentos']for i in items)==821
data=dict(fecha='2026-09-19',instrumentos_antes=41,instrumentos_despues=68,fragmentos_despues=4121,temas_despues=1100,altas=items,anteriores_sin_cambios=True,pendientes_prioritarios=['RAD-033: bases completas de desarrollo mixto CFE'],referencias_ampliadas_por_cotejar=76)
(R/'INCORPORACION.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
md=['# Incorporación de pendientes · 19 de septiembre de 2026','','**27 incorporaciones verificadas. El acervo pasa de 41 a 68 instrumentos, con 4,121 fragmentos y 1,100 entradas de estructura.** Los registros anteriores permanecen idénticos.','','## Instrumentos incorporados','','| Instrumento | Fragmentos | Fuente |','|---|---:|---|']
cards=[]
for i in items:
 md.append(f"| [{i['siglas']}]({i['url']}) · {i['titulo']} | {i['fragmentos']} | [Oficial]({i['fuente']}) |")
 cards.append(f'<article data-search="{esc((i["siglas"]+" "+i["titulo"]+" "+i["familia"]).lower())}"><p class="tag">{esc(i["familia"])}</p><h2>{esc(i["siglas"])}</h2><p>{esc(i["titulo"])}</p><small>{i["fecha"]} · {i["fragmentos"]} fragmentos</small><nav><a href="{i["url"]}">Abrir en el acervo →</a><a href="{i["fuente"]}" target="_blank" rel="noopener noreferrer">Fuente oficial ↗</a></nav></article>')
limits=['Totales calculados a partir de los cotejos.', 'Los planes se organizan por apartados y anexos; biocombustibles conserva sus 22 formularios completos. Los seis formatos CONUEE se muestran en ocho imágenes; su texto interior no tiene OCR.', 'PLADESE: la tabla A2.1 y su título aparentemente discordante coinciden con el PDF oficial, página 108. La nota editorial documenta la observación, sin alterar los datos publicados.', 'Las reformas se identifican como modificaciones, sin presentarlas como leyes o reglamentos completos. REFORMAS-FMP-LOAPF cubre sólo los artículos Noveno y Décimo, sus transitorios y el cierre común del decreto; las otras ocho leyes no se duplican.', 'Sólo LCNE tiene un mapa de páginas para el visor PDF sincronizado. Cargar el texto, las tablas y figuras de estos documentos no crea automáticamente ese mapa.', 'Se cargó texto publicado, sin certificar vigencia ni elaborar versiones consolidadas. No se incorporaron PDFs ni imágenes al repositorio Git.']
# Totales calculados de los cotejos, no aproximaciones manuales.
c=[x for f in folders for x in load(f/'COTEJO-FUENTES.json')]
limits[0]=f"Se preservaron {sum(x['tablas']for x in c):,} tablas HTML, sus {sum(x['celdas']for x in c):,} celdas y {sum(x['graficos']for x in c)} figuras oficiales por liga. Las 30 casillas gráficas de cogeneración se representan como casillas de lectura. No son formularios de envío de datos."
pending='Del bloque prioritario queda RAD-033: el repositorio oficial de desarrollo mixto contiene dos formularios PDF, los lineamientos, dos hojas XLSX y un calendario PNG; no se identificaron bases completas. El inventario ampliado mantiene otras referencias por cotejar: 76 en total, incluida RAD-033. No se marcan como cargadas ni se presentan proyectos o avisos como normas finales.'
md+=['','## Alcance y comprobaciones','']+['- '+s for s in limits]+['','## Pendientes','',pending,'','[Carpeta oficial de desarrollo mixto](https://repositorio.energia.gob.mx/index.php/s/ee3CNyFKLAygaCp) · [Inventario actualizado](../inventario-radar-2026-09-19/INVENTARIO.html)']
(R/'INCORPORACION.md').write_text('\n'.join(md)+'\n',encoding='utf8')
page='''<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>27 incorporaciones · Acervo SENER</title><style>
:root{color-scheme:light dark;--bg:#f8f7f4;--paper:#fff;--text:#292929;--border:#dedbd6;--accent:#9b2247;--green:#1e5b4f}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.65 system-ui,sans-serif;border-top:5px solid var(--accent)}main{max-width:1160px;margin:auto;padding:36px 24px}header{padding-bottom:24px;border-bottom:1px solid var(--border)}h1{font:700 clamp(2rem,4vw,3.2rem)/1.1 Georgia,serif;max-width:800px}h2{font:700 1.12rem/1.3 system-ui;overflow-wrap:anywhere}.tag{font-size:12px;letter-spacing:.07em;text-transform:uppercase;color:var(--green);font-weight:700}a{color:var(--accent);text-underline-offset:4px}input{display:block;width:100%;font:inherit;border:1px solid var(--border);padding:14px;background:var(--paper);color:var(--text);border-radius:8px;margin:24px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:16px}article{background:var(--paper);border:1px solid var(--border);border-radius:10px;padding:22px;display:flex;flex-direction:column}article p{margin:8px 0;overflow-wrap:anywhere}article nav{display:flex;flex-wrap:wrap;gap:14px;margin-top:auto;padding-top:18px}small{color:var(--green)}section.note{padding:24px;background:var(--paper);border:1px solid var(--border);border-left:4px solid var(--accent);margin:24px 0}li{margin:12px 0}[hidden]{display:none!important}@media(max-width:500px){main{padding:24px 16px}.grid{grid-template-columns:1fr}}@media(prefers-color-scheme:dark){:root{--bg:#191a1a;--paper:#242626;--text:#eee;--border:#484545;--accent:#efa2ba;--green:#a5cfbe}}</style><main><header><p class="tag">Secretaría de Energía · Revisión del acervo · 19 septiembre 2026</p><h1>27 incorporaciones verificadas</h1><p><strong>68 instrumentos · 4,121 fragmentos · 1,100 entradas de estructura</strong></p><p>Los 41 instrumentos anteriores se conservaron sin cambios. Las nuevas publicaciones mantienen su estructura y su fuente oficial.</p><a href="/#acervo">Abrir el acervo</a> · <a href="../inventario-radar-2026-09-19/INVENTARIO.html">Consultar inventario completo</a></header>'''
page+='<section class="note"><h2>Qué sigue pendiente</h2><p>'+esc(pending)+'</p><a href="https://repositorio.energia.gob.mx/index.php/s/ee3CNyFKLAygaCp">Material oficial de desarrollo mixto ↗</a></section><label for="f">Filtrar las incorporaciones</label><input id="f" type="search" placeholder="Nombre, siglas o tema…"><div class="grid">'+''.join(cards)+'</div><section class="note"><h2>Alcance de la carga</h2><ul>'+''.join('<li>'+esc(x)+'</li>'for x in limits)+'</ul></section><p><a href="INCORPORACION.json">Evidencia en JSON</a> · <a href="INCORPORACION.md">Resumen en texto</a></p></main><script>document.getElementById("f").addEventListener("input",e=>{const q=e.target.value.toLocaleLowerCase("es");document.querySelectorAll("article").forEach(a=>a.hidden=!a.dataset.search.includes(q))})</script></html>'
(R/'INCORPORACION.html').write_text(page,encoding='utf8')
public=R.parents[1]/'public/revision-acervo'/R.name;public.mkdir(parents=True,exist_ok=True)
for n in ['INCORPORACION.html','INCORPORACION.md','INCORPORACION.json']:(public/n).write_bytes((R/n).read_bytes())
print(json.dumps(dict(incorporados=27,fragmentos_nuevos=821,tablas=sum(x['tablas']for x in c),celdas=sum(x['celdas']for x in c),figuras=sum(x['graficos']for x in c)),ensure_ascii=False))
