import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
const dir=new URL('.',import.meta.url),map=JSON.parse(readFileSync(new URL('map.json',dir),'utf8')),pack=JSON.parse(readFileSync(new URL('articulos-verificados.json',dir),'utf8')),audit=JSON.parse(readFileSync(new URL('cotejo.json',dir),'utf8'));
const path=new URL('../../public/reader-sources/manifest.v1.json',dir);let raw=readFileSync(path,'utf8');const manifest=JSON.parse(raw),articles=pack.articulos,expected=new Map(articles.map(a=>[a.id,a]));
const sha='8c7956f18f1e1c92ae928fba2e72ab33ca5a86565116b83cf869a39ab1b2de8b',official='https://dof.gob.mx/abrirPDF.php?anio=2026&archivo=30042026-MAT.pdf&repo=',instrument='f17cb3b7-0f09-5a97-8c90-47812c921dbd';
if(pack.ley.id!==instrument||map.source.originalUrl!==official||map.source.id!==`dof-matutina-2026-04-30-${sha.slice(0,12)}`||map.source.sha256!==sha||map.source.pageCount!==314||articles.length!==4||Object.keys(map.articles).length!==4||audit.paginasImpresasDelInstrumento.join(',')!=='189,189')throw new Error('El cotejo no cubre los cuatro fragmentos oficiales.');
for(const[id,e]of Object.entries(map.articles)){const a=expected.get(id);if(!a||e.sourceId!==map.source.id||e.label!==a.identificador||e.type!==a.tipo_articulo||e.contentSha256!==createHash('sha256').update(a.contenido,'utf8').digest('hex')||!e.anchors.length||e.pageNumbers.length!==1||e.pageNumbers[0]!==189)throw new Error(`Cotejo incompleto: ${e.label}`);for(const x of e.anchors){const p=map.source.pages.find(v=>v.number===x.page),[x0,y0,x1,y1]=x.bbox;if(!p||![x0,y0,x1,y1].every(Number.isFinite)||!(0<=x0&&x0<x1&&x1<=p.width&&0<=y0&&y0<y1&&y1<=p.height))throw new Error(`Coordenada inválida: ${e.label}`);}}
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),old=manifest.sources[map.source.id];if(old&&!same(old,map.source))throw new Error('La fuente ya existe con contenido distinto.');const newMaps=Object.fromEntries(Object.entries(map.articles).filter(([id])=>!manifest.articles[id]));for(const[id,e]of Object.entries(map.articles))if(manifest.articles[id]&&!same(manifest.articles[id],e))throw new Error(`Mapa distinto para ${id}.`);
const sources=old?{}:{[map.source.id]:map.source};if(!Object.keys(sources).length&&!Object.keys(newMaps).length)console.log('Los cuatro mapas ya están publicados.');else{const eol=raw.includes('\r\n')?'\r\n':'\n',indent=v=>JSON.stringify(v,null,2).split('\n').map((l,i)=>i?`  ${l}`:l).join(eol);if(Object.keys(sources).length){const boundary=/\r?\n  },\r?\n  "articles"/;if(!boundary.test(raw))throw new Error('Cierre de sources no encontrado.');const row=`    ${JSON.stringify(map.source.id)}: ${indent(map.source)}`;raw=raw.replace(boundary,`,${eol}${row}${eol}  },${eol}  "articles"`);}if(Object.keys(newMaps).length){const boundary=/\r?\n  }\r?\n}\r?\n?$/;if(!boundary.test(raw))throw new Error('Cierre de articles no encontrado.');const rows=Object.entries(newMaps).map(([id,v])=>`    ${JSON.stringify(id)}: ${indent(v)}`).join(`,${eol}`);raw=raw.replace(boundary,`,${eol}${rows}${eol}  }${eol}}`);}raw=raw.replace(`"revision": ${manifest.revision}`,`"revision": ${manifest.revision+1}`).replace(/("verifiedAt":\s*)"[^"]+"/,(_,p)=>`${p}"${new Date().toISOString()}"`);JSON.parse(raw);writeFileSync(path,raw);console.log(`Manifiesto ${manifest.revision} → ${manifest.revision+1}; fuente ${Object.keys(sources).length}, mapas ${Object.keys(newMaps).length}.`);}


