import {readFileSync,writeFileSync} from 'node:fs';import{createHash}from'node:crypto';
const dir=new URL('.',import.meta.url),map=JSON.parse(readFileSync(new URL('map.json',dir),'utf8'));
const pack=JSON.parse(readFileSync(new URL('../incorporacion-convocatorias-2026-09-17/CONV-GEN-1-M2-carga.json',dir),'utf8'));
const audit=JSON.parse(readFileSync(new URL('cotejo.json',dir),'utf8')),path=new URL('../../public/reader-sources/manifest.v1.json',dir);let raw=readFileSync(path,'utf8');const manifest=JSON.parse(raw);
const official=pack.articulos.filter(a=>!a.identificador.toLowerCase().startsWith('nota editorial')),expected=new Map(official.map(a=>[a.id,a])),ids=Object.keys(map.articles);
const sha='7f5b3270512bace265139239071a007dd150e184e7a24f869055da27afba2360';
if(pack.ley.id!=='10c059c7-bfa4-5ec0-9ae6-bf1d8a35a637'||map.source.originalUrl!=='https://sidof.segob.gob.mx/notas/getNewsletter/10-11-2025/Matutina/324043'||map.source.id!==`dof-matutina-2025-11-10-${sha.slice(0,12)}`||map.source.pageCount!==438||map.source.sha256!==sha||official.length!==5||ids.length!==5||ids.some(id=>!expected.has(id))||audit.fragmentosOficiales!==5||audit.paginasImpresasDelInstrumento.join(',')!=='142')throw new Error('El cotejo no cubre los cinco fragmentos oficiales.');
for(const[id,e]of Object.entries(map.articles)){const a=expected.get(id);if(e.sourceId!==map.source.id||e.label!==a.identificador||e.type!==a.tipo_articulo||e.contentSha256!==createHash('sha256').update(a.contenido,'utf8').digest('hex')||!e.anchors.length||e.pageNumbers.join(',')!=='142')throw new Error(`Cotejo incompleto: ${a.identificador}`);for(const x of e.anchors){const p=map.source.pages.find(v=>v.number===x.page),[x0,y0,x1,y1]=x.bbox;if(!p||![x0,y0,x1,y1].every(Number.isFinite)||!(0<=x0&&x0<x1&&x1<=p.width&&0<=y0&&y0<y1&&y1<=p.height))throw new Error(`Coordenada inválida: ${a.identificador}`);}}
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),old=manifest.sources[map.source.id];if(old&&!same(old,map.source))throw new Error('Edición ya registrada con otra huella.');const prior=Object.fromEntries(Object.entries(manifest.articles).filter(([,e])=>e.sourceId===map.source.id));if(Object.keys(prior).length&&!same(prior,map.articles))throw new Error('Existe mapa parcial diferente.');for(const[id,e]of Object.entries(map.articles))if(manifest.articles[id]&&!same(manifest.articles[id],e))throw new Error(`Mapa distinto para ${id}.`);
const sources=old?{}:{[map.source.id]:map.source},articles=Object.fromEntries(Object.entries(map.articles).filter(([id])=>!manifest.articles[id]));if(!Object.keys(sources).length&&!Object.keys(articles).length)console.log('Los cinco mapas ya están publicados.');else{
const eol=raw.includes('\r\n')?'\r\n':'\n',indent=v=>JSON.stringify(v,null,2).split('\n').map((s,i)=>i?`  ${s}`:s).join(eol);
if(Object.keys(sources).length){const b=`${eol}  },${eol}  "articles": {`;if(!raw.includes(b))throw new Error('Cierre de fuentes no encontrado.');const rows=Object.entries(sources).map(([id,v])=>`    ${JSON.stringify(id)}: ${indent(v)}`).join(`,${eol}`);raw=raw.replace(b,`,${eol}${rows}${eol}  },${eol}  "articles": {`);}
if(Object.keys(articles).length){const b=/\r?\n  }\r?\n}\r?\n?$/;if(!b.test(raw))throw new Error('Cierre de mapas no encontrado.');const rows=Object.entries(articles).map(([id,v])=>`    ${JSON.stringify(id)}: ${indent(v)}`).join(`,${eol}`);raw=raw.replace(b,`,${eol}${rows}${eol}  }${eol}}`);}
raw=raw.replace(`"revision": ${manifest.revision}`,`"revision": ${manifest.revision+1}`).replace(/("verifiedAt":\s*)"[^"]+"/,(_,p)=>`${p}"${new Date().toISOString()}"`);JSON.parse(raw);writeFileSync(path,raw);console.log(`Manifiesto ${manifest.revision} → ${manifest.revision+1}; ${Object.keys(articles).length} mapas agregados.`);}
